# Generated by Django 3.2.5 on 2022-08-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0002_dweet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dweet',
            options={'ordering': ['-created_at']},
        ),
    ]
