# Generated by Django 3.2.5 on 2022-08-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0003_alter_dweet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dweet',
            options={},
        ),
    ]
